# # AEMO ISP source coverage and ownership
#
# ParseISP reads AEMO workbooks and model files, user-supplied build-out sheets,
# and preprocessing workbooks created from AEMO outlook data.
# The tables connect each source selection to the subject it defines, the
# package parameters that supplement it, and the mappings applied before
# outputs are written. Bulk time-series traces are described separately in
# [Trace coverage](../../../editions/trace-coverage.md).

using DataFrames
using TOML

const REPO_ROOT = normpath(get(ENV, "ParseISP_DOCS_REPO_ROOT", joinpath(@__DIR__, "..", "..", "..", "..")))

include(joinpath(REPO_ROOT, "docs", "utils", "ParseISPDocUtils.jl"))
import .ParseISPDocUtils

coverage = ParseISPDocUtils.coverage_document(REPO_ROOT)
source_reads = ParseISPDocUtils.coverage_table(coverage, "source_read")
parameter_families = ParseISPDocUtils.coverage_table(coverage, "parameter_family")
mapping_families = ParseISPDocUtils.coverage_table(coverage, "mapping_family")
registry = TOML.parsefile(joinpath(REPO_ROOT, "docs", "config", "page-registry.toml"))
page_titles = Dict(page["id"] => page["title"] for page in registry["page"])
page_titles["editions/trace-coverage.md"] = "Trace coverage"

length(unique(source_reads.id)) == nrow(source_reads) || error("source-read IDs must be unique")
length(unique(parameter_families.id)) == nrow(parameter_families) || error("parameter-family IDs must be unique")
length(unique(mapping_families.id)) == nrow(mapping_families) || error("mapping-family IDs must be unique")
all(source_reads.status .== "active") || error("the source map contains an inactive entry")
all(.!isempty.(source_reads.owner)) || error("every source selection requires a subject page")
nothing #hide

# ## Source-read classifications
#
# The source map distinguishes AEMO files, preprocessing workbooks, user
# inputs, parsed structures, and trace material.

source_classifications = combine(groupby(source_reads, :classification), nrow => :items)
sort!(source_classifications, :classification)
source_classifications.classification = ParseISPDocUtils.friendly_classification.(source_classifications.classification)
ParseISPDocUtils.markdown_table(
    source_classifications;
    column_labels = ["Source type", "Selections"],
)
#-

# ## Source subjects
#
# Each source selection belongs to the subject page that explains its fields
# and role. Repeated reads remain separate when ParseISP uses them in separate
# transformations, and DSP selections are expanded by scenario, region, and
# season.

source_owner_summary = combine(groupby(source_reads, [:owner, :classification]), nrow => :items)
sort!(source_owner_summary, [:owner, :classification])
source_owner_summary.classification = ParseISPDocUtils.friendly_classification.(source_owner_summary.classification)
source_owner_summary.owner = [get(page_titles, owner, owner) for owner in source_owner_summary.owner]
rename!(source_owner_summary, :owner => :subject_page, :classification => :source_type)
ParseISPDocUtils.markdown_table(
    source_owner_summary;
    column_labels = ["Subject page", "Source type", "Selections"],
)
#-

# ## ParseISP-generated intermediates
#
# These workbooks are active parser inputs, but they are generated by ParseISP preprocessing from AEMO outlook workbooks.
# They are not original AEMO publications and are therefore kept in a distinct classification.

auxiliary_reads = select(
    filter(:classification => ==("pisp_generated_intermediate"), source_reads),
    :artefact,
    :worksheet,
    :owner,
    :notes,
)
auxiliary_reads.owner = [get(page_titles, owner, owner) for owner in auxiliary_reads.owner]
rename!(auxiliary_reads, :artefact => :file, :owner => :subject_page)
ParseISPDocUtils.markdown_table(
    auxiliary_reads;
    column_labels = ["File", "Worksheet", "Subject page", "Use"],
)
#-

# ## Parameter-file ownership
#
# `ParseISPparameters.jl` includes six files.
# The table pairs each file with the subject page that explains its values and effects.

parameter_owners = select(parameter_families, :source_path, :family, :owner, :notes)
parameter_owners.owner = [get(page_titles, owner, owner) for owner in parameter_owners.owner]
rename!(parameter_owners, :owner => :subject_page)
ParseISPDocUtils.markdown_table(
    parameter_owners;
    column_labels = ["Package file", "Parameter family", "Subject page", "Use"],
)
#-

# ## Mapping-family ownership
#
# The mapping table covers maintained constants and parser lookup families, including generation, storage, retirement, hydro, geography, scenario, reliability, DSP, EV, source-file, build-out, and output-schema mappings.
# Runtime dictionaries are classified as parsed representations rather than independent maintained constants.

mapping_owners = select(mapping_families, :family, :classification, :owner, :source_path)
mapping_owners.classification = ParseISPDocUtils.friendly_classification.(mapping_owners.classification)
mapping_owners.owner = [get(page_titles, owner, owner) for owner in mapping_owners.owner]
rename!(mapping_owners, :classification => :source_type, :owner => :subject_page)
ParseISPDocUtils.markdown_table(
    mapping_owners;
    column_labels = ["Mapping", "Source type", "Subject page", "Package file"],
)
#-

# ## Edition coverage
#
# ISP 2024 rows identify the package readers and mappings used by the dataset
# workflow. ISP 2026 rows identify the files, selections, and source subjects
# used by the source and comparison pages.
# The machine-readable authority is `docs/config/source-material-coverage.toml` in the repository.
