# # AEMO ISP source coverage and ownership
#
# This ledger defines the documentation owner for every active source selection used by the current PISP workflow, together with the package parameter and mapping families that shape the resulting datasets.
# It distinguishes original AEMO material from parsed representations, PISP-generated intermediates, package conventions, user inputs, PISP outputs, and bulk trace material outside this documentation family.

using DataFrames

const REPO_ROOT = normpath(get(ENV, "PISP_DOCS_REPO_ROOT", joinpath(@__DIR__, "..", "..", "..", "..")))

include(joinpath(REPO_ROOT, "docs", "utils", "PISPDocUtils.jl"))
import .PISPDocUtils

coverage = PISPDocUtils.coverage_document(REPO_ROOT)
source_reads = PISPDocUtils.coverage_table(coverage, "source_read")
parameter_families = PISPDocUtils.coverage_table(coverage, "parameter_family")
mapping_families = PISPDocUtils.coverage_table(coverage, "mapping_family")

length(unique(source_reads.id)) == nrow(source_reads) || error("source-read IDs must be unique")
length(unique(parameter_families.id)) == nrow(parameter_families) || error("parameter-family IDs must be unique")
length(unique(mapping_families.id)) == nrow(mapping_families) || error("mapping-family IDs must be unique")
all(source_reads.status .== "active") || error("the published source-read ledger contains a non-active entry")
all(.!isempty.(source_reads.owner)) || error("every source read requires a canonical documentation owner")
nothing #hide

# ## Source-read classifications
#
# The active implementation reads AEMO workbooks and model CSVs, user-supplied build-out sheets, and PISP-generated `Auxiliary/` workbooks.
# Trace payloads are documented under trace coverage; this ledger records their source-read ownership.

source_classifications = combine(groupby(source_reads, :classification), nrow => :active_items)
sort!(source_classifications, :classification)
source_classifications.classification = PISPDocUtils.friendly_classification.(source_classifications.classification)
PISPDocUtils.markdown_table(source_classifications)
#-

# ## Canonical owners
#
# A subject page owns each source selection.
# Repeated reads remain separate ledger entries when the current implementation executes them separately, and dynamic DSP selections are expanded by scenario, region, and season.

source_owner_summary = combine(groupby(source_reads, [:owner, :classification]), nrow => :items)
sort!(source_owner_summary, [:owner, :classification])
source_owner_summary.classification = PISPDocUtils.friendly_classification.(source_owner_summary.classification)
PISPDocUtils.markdown_table(source_owner_summary)
#-

# ## PISP-generated intermediates
#
# These workbooks are active parser inputs, but they are generated by PISP preprocessing from AEMO outlook workbooks.
# They are not original AEMO publications and are therefore kept in a distinct classification.

auxiliary_reads = select(
    filter(:classification => ==("pisp_generated_intermediate"), source_reads),
    :artefact,
    :worksheet,
    :owner,
    :notes,
)
PISPDocUtils.markdown_table(auxiliary_reads)
#-

# ## Parameter-file ownership
#
# `PISPparameters.jl` includes six files.
# The table pairs each file with the subject page that explains its values and effects.

parameter_owners = select(parameter_families, :source_path, :family, :owner, :notes)
PISPDocUtils.markdown_table(parameter_owners)
#-

# ## Mapping-family ownership
#
# The mapping ledger covers maintained constants and parser-local lookup families, including generation, storage, retirement, hydro, geography, scenario, reliability, DSP, EV, source-file, build-out, and output-schema mappings.
# Runtime dictionaries are classified as parsed representations rather than independent maintained constants.

mapping_owners = select(mapping_families, :family, :classification, :owner, :source_path)
mapping_owners.classification = PISPDocUtils.friendly_classification.(mapping_owners.classification)
PISPDocUtils.markdown_table(mapping_owners)
#-

# ## How to read the ledger
#
# ISP 2024 rows describe implementation evidence in the current package.
# ISP 2026 has no integrated PISP preprocessing or dataset workflow, so its pages report observed source structure and mark semantic correspondences for review instead of presenting them as implemented mappings.
# The machine-readable authority is `docs/config/source-material-coverage.toml` in the repository.
