const ESS_TEMPLATE_FIELDS = [
    "tech", "type", "investment", "active", "ch_eff", "dch_eff", "eini", "emin",
    "pmin", "lmin", "fullout", "partialout", "mttrfull", "mttrpart", "inertia",
    "powerfactor", "ffr", "pfr", "res2", "res3", "fr_db", "fr_ad", "fr_dt",
    "fr_frt", "fr_fr", "n", "contingency",
]

const GEN_TEMPLATE_FIELDS = [
    "fuel", "tech", "type", "forate", "fullout", "partialout", "derate", "mttrfull",
    "mttrpart", "pmin", "rup", "rdw", "investment", "active", "cvar", "cfuel", "cvom",
    "cfom", "co2", "slope", "hrate", "pfrmax", "g", "inertia", "ffr", "pfr", "res2",
    "res3", "powerfactor", "n", "contingency", "down_time", "up_time", "last_state",
    "last_state_period", "last_state_output", "start_up_cost", "shut_down_cost",
    "start_up_time", "shut_down_time",
]

const ESS_FIELD_SOURCES = Dict(
    "tech" => "PISP default",
    "type" => "PISP default",
    "investment" => "PISP default",
    "active" => "PISP default",
    "ch_eff" => "ISP workbook — Storage properties",
    "dch_eff" => "ISP workbook — Storage properties",
    "eini" => "PISP default",
    "emin" => "PISP default",
    "pmin" => "PISP default",
    "lmin" => "PISP default",
    "fullout" => "ISP workbook — Generator Reliability Settings",
    "partialout" => "PISP default",
    "mttrfull" => "ISP workbook — Generator Reliability Settings",
    "mttrpart" => "PISP default",
    "inertia" => "PISP default",
    "powerfactor" => "PISP default",
    "ffr" => "PISP default",
    "pfr" => "PISP default",
    "res2" => "PISP default",
    "res3" => "PISP default",
    "fr_db" => "PISP default",
    "fr_ad" => "PISP default",
    "fr_dt" => "PISP default",
    "fr_frt" => "PISP default",
    "fr_fr" => "PISP default",
    "n" => "PISP default",
    "contingency" => "PISP default",
)

const GEN_FIELD_SOURCES = Dict(
    "fuel" => "PISP default",
    "tech" => "PISP default",
    "type" => "PISP default",
    "forate" => "ISP workbook — Generator Reliability Settings (derived)",
    "fullout" => "ISP workbook — Generator Reliability Settings",
    "partialout" => "PISP default",
    "derate" => "PISP default",
    "mttrfull" => "ISP workbook — Generator Reliability Settings",
    "mttrpart" => "PISP default",
    "pmin" => "PISP default",
    "rup" => "ISP workbook — Max Ramp Rates",
    "rdw" => "ISP workbook — Max Ramp Rates",
    "investment" => "PISP default",
    "active" => "PISP default",
    "cvar" => "ISP workbook — New Entrant Data Summary",
    "cfuel" => "ISP workbook — New Entrant Data Summary",
    "cvom" => "ISP workbook — New Entrant Data Summary",
    "cfom" => "ISP workbook — New Entrant Data Summary",
    "co2" => "ISP workbook — New Entrant Data Summary",
    "slope" => "PISP default",
    "hrate" => "ISP workbook — New Entrant Data Summary",
    "pfrmax" => "PISP default",
    "g" => "PISP default",
    "inertia" => "PISP default",
    "ffr" => "PISP default",
    "pfr" => "PISP default",
    "res2" => "PISP default",
    "res3" => "PISP default",
    "powerfactor" => "PISP default",
    "n" => "PISP default",
    "contingency" => "PISP default",
    "down_time" => "PISP default",
    "up_time" => "PISP default",
    "last_state" => "PISP default",
    "last_state_period" => "PISP default",
    "last_state_output" => "PISP default",
    "start_up_cost" => "PISP default",
    "shut_down_cost" => "PISP default",
    "start_up_time" => "PISP default",
    "shut_down_time" => "PISP default",
)

const BUILDOUT_SOURCE_PREFIXES = ("ISP workbook", "Published report", "PISP default")

const ESS_PLACEHOLDER_ORIGINS = Dict(
    "id_ess" => "Sequential identifier generated by PISP.",
    "name" => "Generated as `uppercase(tech * \"_\" * subregion) * \"_NEW\"`.",
    "alias" => "Set equal to the generated name.",
    "capacity" => "Read from the build-out workbook.",
    "id_bus" => "Looked up from the workbook subregion in the current bus table.",
    "emax" => "Computed as duration in hours multiplied by workbook capacity.",
    "pmax" => "Set to workbook capacity.",
    "lmax" => "Set to workbook capacity.",
    "longitude" => "Set explicitly to `0.0` by the build-out parser.",
    "latitude" => "Set explicitly to `0.0` by the build-out parser.",
)

const GEN_PLACEHOLDER_ORIGINS = Dict(
    "id_gen" => "Sequential identifier generated by PISP.",
    "name" => "Generated as `uppercase(tech * \"_\" * subregion) * \"_NEW\"`.",
    "alias" => "Set equal to the generated name.",
    "capacity" => "Read from the build-out workbook.",
    "id_bus" => "Looked up from the workbook subregion in the current bus table.",
    "pmax" => "Set to workbook capacity.",
    "latitude" => "Set explicitly to `0.0` by the build-out parser.",
    "longitude" => "Set explicitly to `0.0` by the build-out parser.",
)

# Wraps an identifier in Markdown inline-code backticks. `markdown_table` is called with
# `allow_markdown_in_cells = true` for these reference tables, so the backticks survive
# rendering instead of being escaped like plain cell text.
code_span(value) = "`" * string(value) * "`"

function buildout_technology_rows()
    rows = NamedTuple[]
    for label in sort(collect(PISP._BUILDOUT_ESS_TECHS))
        push!(rows, (
            buildout_label = label,
            output_table = "ESS",
            template_key = label,
            duration_h = PISP._BESS_DURATION_H[label],
        ))
    end
    for label in sort(collect(PISP._BUILDOUT_GEN_TECHS))
        push!(rows, (
            buildout_label = label,
            output_table = "Generator",
            template_key = String(PISP._BUILDOUT_GEN_TECH_KEY[label]),
            duration_h = missing,
        ))
    end
    return rows
end

function buildout_origin_rows()
    return [
        (output = "ESS static row", field_group = "Build-out workbook", rule = "`tech`, `subregion`, and `capacity` select, locate, and size the asset."),
        (output = "ESS static row", field_group = "Generated or looked up", rule = "PISP generates `id_ess`, `name`, and `alias`, and resolves `id_bus` from the subregion."),
        (output = "ESS static row", field_group = "Calculated or explicit", rule = "`emax = duration_h × capacity`; `pmax = capacity`; `lmax = capacity`; coordinates are `0.0`."),
        (output = "ESS static row", field_group = "Stored default", rule = "The 27 non-placeholder fields listed below come from `PISP.params_buildout_bess`."),
        (output = "ESS unit-count schedule", field_group = "Build-out workbook and generated", rule = "The workbook supplies `year` and `n`; PISP adds scenario IDs, row IDs, and `DateTime(year, 1, 1)`."),
        (output = "Generator static row", field_group = "Build-out workbook", rule = "`tech`, `subregion`, and `capacity` select, locate, and size the asset."),
        (output = "Generator static row", field_group = "Generated or looked up", rule = "PISP generates `id_gen`, `name`, and `alias`, and resolves `id_bus` from the subregion."),
        (output = "Generator static row", field_group = "Calculated or explicit", rule = "`pmax = capacity`; coordinates are `0.0`."),
        (output = "Generator static row", field_group = "Stored default", rule = "The 40 non-placeholder fields listed below come from `PISP.params_buildout_gen`."),
        (output = "Generator unit-count schedule", field_group = "Build-out workbook and generated", rule = "The workbook supplies `year` and `n`; PISP adds scenario IDs, row IDs, and `DateTime(year, 1, 1)`."),
    ]
end

function buildout_placeholder_rows()
    rows = NamedTuple[]
    for field in sort(collect(keys(ESS_PLACEHOLDER_ORIGINS)))
        push!(rows, (output_table = "ESS", field = field, applied_rule = ESS_PLACEHOLDER_ORIGINS[field]))
    end
    for field in sort(collect(keys(GEN_PLACEHOLDER_ORIGINS)))
        push!(rows, (output_table = "Generator", field = field, applied_rule = GEN_PLACEHOLDER_ORIGINS[field]))
    end
    return rows
end

function template_comparison_rows(kind::Symbol)
    if kind == :ess
        labels = sort(collect(PISP._BUILDOUT_ESS_TECHS))
        fields = ESS_TEMPLATE_FIELDS
        sources = ESS_FIELD_SOURCES
        templates = Dict(label => PISP.params_buildout_bess[Symbol(label)] for label in labels)
    elseif kind == :gen
        labels = sort(collect(PISP._BUILDOUT_GEN_TECHS))
        fields = GEN_TEMPLATE_FIELDS
        sources = GEN_FIELD_SOURCES
        templates = Dict(label => PISP.params_buildout_gen[PISP._BUILDOUT_GEN_TECH_KEY[label]] for label in labels)
    else
        error("kind must be :ess or :gen")
    end

    return [(
        field = field,
        source = sources[field],
        values = Dict(label => templates[label][field] for label in labels),
    ) for field in fields]
end

function split_common_rows(rows, labels)
    common = NamedTuple[]
    varying = NamedTuple[]
    for row in rows
        values = [row.values[label] for label in labels]
        if all(==(first(values)), values)
            push!(common, (field = code_span(row.field), value = first(values), source = row.source))
        else
            push!(varying, row)
        end
    end
    return common, varying
end

function comparison_frame(rows, labels)
    table = DataFrame(
        field = [code_span(row.field) for row in rows],
        source = [row.source for row in rows],
    )
    for label in labels
        table[!, Symbol(label)] = [row.values[label] for row in rows]
    end
    return table
end

function field_metadata_frame(rows)
    return DataFrame(
        field = [code_span(row.field) for row in rows],
        source = [row.source for row in rows],
    )
end

function technology_value_frame(rows, labels)
    table = DataFrame(buildout_label = [code_span(label) for label in labels])
    for row in rows
        table[!, Symbol(row.field)] = [row.values[label] for label in labels]
    end
    return table
end

function buildout_reference_tables()
    ess_labels = sort(collect(PISP._BUILDOUT_ESS_TECHS))
    ess_rows = template_comparison_rows(:ess)
    ess_common, ess_varying = split_common_rows(ess_rows, ess_labels)

    gen_labels = sort(collect(PISP._BUILDOUT_GEN_TECHS))
    gen_rows = template_comparison_rows(:gen)
    gen_common, gen_varying = split_common_rows(gen_rows, gen_labels)

    technology_rows = [
        (buildout_label = code_span(row.buildout_label), output_table = row.output_table,
         template_key = code_span(row.template_key), duration_h = row.duration_h)
        for row in buildout_technology_rows()
    ]
    placeholder_rows = [
        (output_table = row.output_table, field = code_span(row.field), applied_rule = row.applied_rule)
        for row in buildout_placeholder_rows()
    ]

    return (
        technology = DataFrame(technology_rows),
        origins = DataFrame(buildout_origin_rows()),
        placeholders = DataFrame(placeholder_rows),
        ess_common = DataFrame(ess_common),
        ess_varying_fields = field_metadata_frame(ess_varying),
        ess_varying_values = technology_value_frame(ess_varying, ess_labels),
        gen_common = DataFrame(gen_common),
        gen_varying = comparison_frame(gen_varying, gen_labels),
    )
end

function _section(text, start_marker, end_marker)
    start_range = findfirst(start_marker, text)
    start_range === nothing && error("missing parser marker: $start_marker")
    start_index = first(start_range)
    end_range = findnext(end_marker, text, last(start_range) + 1)
    end_range === nothing && error("missing parser marker: $end_marker")
    return text[start_index:first(end_range)-1]
end

function _template_keys(text)
    return Set(match.captures[1] for match in eachmatch(r"p\[\"([^\"]+)\"\]", text))
end

function parser_template_fields(parser_path)
    text = read(parser_path, String)
    ess = union(
        _template_keys(_section(text, "function add_buildout_ess!", "function add_buildout_gen!")),
        _template_keys(_section(text, "function _add_buildout_ess_sc!", "function _add_buildout_gen_sc!")),
    )
    gen = union(
        _template_keys(_section(text, "function add_buildout_gen!", "function add_buildouts!")),
        _template_keys(text[findfirst("function _add_buildout_gen_sc!", text)[1]:end]),
    )
    return (ess = ess, gen = gen)
end

function validate_buildout_defaults_contract(parser_path)
    parser_fields = parser_template_fields(parser_path)
    parser_fields.ess == Set(ESS_TEMPLATE_FIELDS) || error("ESS documentation fields differ from parser-consumed keys")
    parser_fields.gen == Set(GEN_TEMPLATE_FIELDS) || error("Generator documentation fields differ from parser-consumed keys")

    Set(keys(ESS_FIELD_SOURCES)) == Set(ESS_TEMPLATE_FIELDS) || error("ESS field sources are incomplete")
    Set(keys(GEN_FIELD_SOURCES)) == Set(GEN_TEMPLATE_FIELDS) || error("Generator field sources are incomplete")

    for source in Iterators.flatten((values(ESS_FIELD_SOURCES), values(GEN_FIELD_SOURCES)))
        any(startswith(source, prefix) for prefix in BUILDOUT_SOURCE_PREFIXES) ||
            error("unsupported build-out source classification: $source")
    end

    for (label, template) in PISP.params_buildout_bess
        for field in ESS_TEMPLATE_FIELDS
            haskey(template, field) || error("ESS template $label is missing $field")
            template[field] === nothing && error("ESS output-effective field $label.$field is `nothing`")
        end
        actual_placeholders = Set(key for (key, value) in template if value === nothing)
        actual_placeholders == Set(keys(ESS_PLACEHOLDER_ORIGINS)) || error("ESS placeholder classification differs for $label")
    end

    for (label, template) in PISP.params_buildout_gen
        for field in GEN_TEMPLATE_FIELDS
            haskey(template, field) || error("Generator template $label is missing $field")
            template[field] === nothing && error("Generator output-effective field $label.$field is `nothing`")
        end
        actual_placeholders = Set(key for (key, value) in template if value === nothing)
        actual_placeholders == Set(keys(GEN_PLACEHOLDER_ORIGINS)) || error("Generator placeholder classification differs for $label")
    end

    return true
end
